rabbitmq:
  mqtt:
    url: tcp://192.168.137.140:1883
    username: guest
    password: guest
    default-topic: testTopic
spring:
  datasource:
    url: jdbc:mysql://192.168.137.140:3307/BackEndList?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    url: redis://192.168.137.140:6379

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
    map-underscore-to-camel-case: true #开启驼峰映射
  global-config:
    db-config:
      id-type: assign_id #生成主键id
